### ISSUE TITLE
[Bug]: Mouse cursor briefly changes to pointing hand when hovering a server in the list

### ISSUE THREAD

**Issue by Dainternetdude** [SwiftcordApp/Swiftcord#102]
### Describe the Bug

**Bug Description**
When moving the mouse over one of the icons representing a server in the sidebar server list, the mouse cursor sometimes briefly (seems to be about 1 frame) changes to the pointing hand cursor instead of the arrow cursor.

I attempted to record a video of the glitch occurring, but it seems that the video did not pick up every instance of the glitch. https://youtu.be/E76HkcnRaMs

**Actual Behaviour**
The pointing hand cursor sometimes briefly appears when hovering server icons.

**Expected Behavior**
The pointing hand cursor should never appear when hovering server icons, the traditional arrow cursor should only be used in this location.

### Reproducing the Bug

1... Hover over a server
2... Repeat until the wrong cursor appears
3... Observe that the wrong cursor has appeared briefly

### Version

0.4.5 (12)

### Category

Other

### Additional Info

macOS 12.5 Monterey
intel macbook 2020

**Comment by cryptoAlgorithm** [comment]
@Dainternetdude Thanks for the bug report. I believe this is due to SwiftUI's buggy cursor implementation, and from discussions in the Discord server I'll probably remove the custom cursor modifiers in the near future.
