### ISSUE TITLE
[Bug]: Additional tabs can be created

### ISSUE THREAD

**Issue by Dainternetdude** [SwiftcordApp/Swiftcord#114]
### Describe the Bug

**Bug Description**
Upon clicking in the menu bar View > Show Tab Bar or View > Show All Tabs, the plus sign button can be clicked to create a new tab. This behaviour is glitchy and is obviously unintended.

**Actual Behaviour**
Tab creation, deletion, & rearrangement is supported.

**Expected Behavior**
There should not be any tabbing behaviour supported, these tab-related buttons should not exist in the view menu.

### Reproducing the Bug

1... click View > Show Tab Bar
2... create a new tab

### Version

0.4.6

### Category

Other

**Comment by cryptoAlgorithm** [comment]
Would removing the option to create tabs as a whole be better, or supporting them properly?

**Comment by Dainternetdude** [comment]
in my opinion it would be better to remove the option to create tabs, as it is not present in the official discord client.

**Comment by cryptoAlgorithm** [comment]
Thanks!
