### ISSUE TITLE
[Bug]: Message are sent twice

### ISSUE THREAD

**Issue by Im-Fran** [SwiftcordApp/Swiftcord#120]
### Describe the Bug

If you write a message to any channel they're sent twice.

### Reproducing the Bug

1. Go to any channel
2. Send a message
3. See that they're sent twice

### Version

0.5.1 (Build 15)

### Category

Sending messages

### Screenshots

![](https://user-images.githubusercontent.com/30329003/195997975-48cc4a95-4bd8-4256-9e82-bd13a38a69eb.mov)

**Comment by cryptoAlgorithm** [comment]
Weird, I can't seem to reproduce that...

https://user-images.githubusercontent.com/64193267/196068112-cb7d05ed-7ba5-45e6-9b95-d0e5690f4a1f.mov

**Comment by Im-Fran** [comment]
Sorry for the daly, I still face this issue, are there any logs I could share?

**Comment by cryptoAlgorithm** [comment]
@Im-Fran nah, I dont think logs would fix this issue. I think it's SwiftUI acting up again, which macOS version are you running on?

**Comment by Im-Fran** [comment]
@cryptoAlgorithm Version 13.0 Beta (22A5365d)

**Comment by cryptoAlgorithm** [comment]
@Im-Fran weird, could you try using the send button to send your message, in case it's something wrong with handing the enter key?

**Comment by Im-Fran** [comment]
@cryptoAlgorithm you're right, using the button is sent once, the enter key is causing sending messages twice :p

**Comment by airsquared** [comment]
I'm getting the same bug on macOS 13.2.1 on a M1 Pro MBP.

**Comment by cryptoAlgorithm** [comment]
@airsquared Thanks for reporting this! I will be releasing a beta release on GitHub actions soon with all the fixes and improvements I've been working on these ~5 months. Stay tuned!

**Comment by cryptoAlgorithm** [comment]
Fixed in release v0.6.1!
