### ISSUE TITLE
[Bug]: Hebrew translation halfway, also no Romanian translation (I can do)

### ISSUE THREAD

**Issue by MDNich** [SwiftcordApp/Swiftcord#128]
### Describe the Bug

**Bug Description**

Not fully translated, and no Romanian translation

**Actual Behaviour**

Half-translated:)

**Expected Behavior**

A full translation :)

### Reproducing the Bug

Easy: launch the app with hebrew localization chosen

### Version

0.5.1

### Category

Other

### Additional Info

I will write a stub of Romanian translations in a PR soon. :)

**Comment by cryptoAlgorithm** [comment]
@MDNich Thanks for pointing out this issue. However, translations are a WIP and will be incomplete as not all string constants in the app make use of localisations, and translations are provided by the community and are bound to be incomplete. If you'd like to chip in some translations to improve their accuracy or completeness, please use the Weblate link as noted above.
