### ISSUE TITLE
[Bug]: Scroll indicator need fullscreen button

### ISSUE THREAD

**Issue by nemoiosdev** [SwiftcordApp/Swiftcord#131]
### Describe the Bug

There is part of a scroll indicator appear bellow full screen button

### Reproducing the Bug

Open the app

I'm using dark mode all the time, so if I turn off dark mode then turn on again, the issue is fixed. But if I close the app(red button) then open again, the issue happen again

### Version

0.15.1

### Category

Other

### Screenshots

![Screen Shot 2022-12-06 at 5 49 06 PM](https://user-images.githubusercontent.com/71942082/205865738-bb0fcbe5-c057-4893-8595-08192cb1484c.png)

**Comment by cryptoAlgorithm** [comment]
@nemoiosdev thanks for reporting this! However, it looks like it's already been reported as issue #129, so I'll have to close this as a duplicate. Do comment on that issue if you have anything to add!
