### ISSUE TITLE
[Bug]: Text doesn't wrap when composing a message

### ISSUE THREAD

**Issue by danieltaylor** [SwiftcordApp/Swiftcord#133]
### Describe the Bug

**Bug Description**
When composing a message, text does not wrap to a new line if the text goes over the length of the input box.

This issue was previously reported in #45.  It was marked as resolved, but seems to have returned in the latest release.

**Actual Behaviour**
Text is cut off.  It is actually there but is not visible.  When the message is sent, everything that was typed shows up as expected.
<img width="587" alt="Screen Shot 2023-01-16 at 5 31 10 PM" src="https://user-images.githubusercontent.com/6980323/212785022-96ee8546-3068-44e9-937d-49f7428dd9e2.png">

**Expected Behavior**
Swiftcord should behave similarly to the Discord app:
<img width="873" alt="Screen Shot 2023-01-16 at 5 32 51 PM" src="https://user-images.githubusercontent.com/6980323/212784917-3692b352-7d06-428e-9be3-684441a4cff3.png">

### Reproducing the Bug

1. Type a somewhat long message.

### Version

0.5.1

### Category

Message rendering

**Comment by cryptoAlgorithm** [comment]
Hi @danieltaylor, may I know what macOS version you're using? This appears to be a bug on macOS 12, and I can't really fix that as its a problem within apple's SwiftUI implementation in the system itself.

**Comment by bnwa** [comment]
Definitely running into this myself on 12.6.3

**Comment by cryptoAlgorithm** [comment]
Fixed by #134, thanks to @ErrorErrorError!
<video src="https://user-images.githubusercontent.com/64193267/218983272-98e85e0b-3a10-4c86-86cc-85538319d8e1.mov" />
