### ISSUE TITLE
[Bug] Folder popover opening cancels server mask animation

### ISSUE THREAD

**Issue by Sjmarf** [SwiftcordApp/Swiftcord#156]
https://github.com/SwiftcordApp/Swiftcord/assets/78750526/613d15d2-586e-4ba3-b4a9-8dc1c6f51858

**Comment by Sjmarf** [comment]
> Arghhh now I've noticed it, I can't unsee it! Since this doesn't appear to happen between servers, it's possibly something to do with one of the fade animations when the mouse is moved on a folder. It's unlikely that its caused by the popover (removing the popover should confirm that) as the popover is a separate view that should not interfere with other SwiftUI animations.

I tried adding a popover to the server icons, which caused this issue to happen between the server icons too. That's what made me notice the bug.

**Comment by cryptoAlgorithm** [comment]
> I tried adding a popover to the server icons, which caused this issue to happen between the server icons too. That's what made me notice the bug.

Wow if it's actually due to the popover, it looks like a bug in SwiftUI again that'll be a major PITA to fix...

**Comment by cryptoAlgorithm** [comment]
Closing as this appears to be a bug within either AppKit or SwiftUI. Since this isn't a breaking issue, I don't feel that messing around for a fix that _might_ exist is worth it.
