### ISSUE TITLE
[Bug]: Stuck logging in

### ISSUE THREAD

**Issue by AstralNexus25** [SwiftcordApp/Swiftcord#167]
### Describe the Bug

**Bug Description**
I enter my username and password, click Log In, and it keeps loading. I've tried different macOS versions (Sonoma dev beta and Ventura), tried different Swiftcord versions, even reinstalled macOS altogether. (dw I backed it up)
I tried a different user account and it turns out that works. That account was inactive for a long time, and I had not updated the username to the latest non-#xxxx format. It is possible that that was the issue, but it really shouldn't be.

**Actual Behaviour**
Entered username, password, click Log In, stuck on spinning discord logo.

**Expected Behavior**
It.. loads?

### Reproducing the Bug

1... Log In
2...Wait..
3...Wait...
... Log out ig

### Version

0.6.1

### Category

Login

### Screenshots

Start screen
<img width="1012" alt="SCR-20230723-rets" src="https://github.com/SwiftcordApp/Swiftcord/assets/96607325/f6c37872-f5ae-42a1-a94a-5a912c50191b">
Login
<img width="1012" alt="SCR-20230723-rewz-2" src="https://github.com/SwiftcordApp/Swiftcord/assets/96607325/7ddb62ba-de14-457d-b5f9-8778dab9c06c">
Loading screen
<img width="1012" alt="SCR-20230723-rfau" src="https://github.com/SwiftcordApp/Swiftcord/assets/96607325/e4b088a9-6852-4b0b-a05a-c45335b782b0">
Eventually the "This is taking a while, want to log out?" button appears
<img width="1012" alt="SCR-20230723-rfco" src="https://github.com/SwiftcordApp/Swiftcord/assets/96607325/91df7881-1f99-4e5c-a505-9174d63901a3">
It crashes after a while (like 5 minutes)
<img width="632" alt="SCR-20230723-rgtv" src="https://github.com/SwiftcordApp/Swiftcord/assets/96607325/e1fdd913-9465-4011-95c3-19405cc5ea8e">

### Additional Info

I did try a different legacy username account (by legacy I mean it still had the #xxxx ending), and surprisingly it logged in fine. This probably isn't useful since it is (hopefully) really unlikely that this is an issue, but just wanted to put that out. Thanks!

### Edit: Attaching the Problem Details and System Configuration log that shows up in the "Swiftcord quit unexpectedly" message if that helps.
[Problem Details and System Configuration.txt](https://github.com/SwiftcordApp/Swiftcord/files/12138917/Problem.Details.and.System.Configuration.txt)

**Comment by crystall1nedev** [comment]
Leaving this here:

```
evaluna@Evas-MacBookPro181 ~ % /Applications/Swiftcord.app/Contents/MacOS/Swiftcord 
2023-07-26T03:52:37-0400 info RobustWebSocket : version=9 ws=wss://gateway.discord.gg/?v=9&encoding=json&compress=zlib-stream [DiscordKitCore] [CONNECT]
2023-07-26T03:52:37-0400 warning RobustWebSocket : [DiscordKitCore] Reconnection in progress, not reconnecting
2023-07-26T03:52:37-0400 info RobustWebSocket : [DiscordKitCore] [CONNECTED]
2023-07-26T03:52:37-0400 info RobustWebSocket : heartbeat_interval=41250 [DiscordKitCore] [HELLO]
2023-07-26T03:52:37-0400 info RobustWebSocket : intents=nil [DiscordKitCore] [IDENTIFY]
2023-07-26T03:52:38-0400 warning RobustWebSocket : error=dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "d", intValue: nil), CodingKeys(stringValue: "user", intValue: nil), CodingKeys(stringValue: "premium_type", intValue: nil)], debugDescription: "Cannot initialize PremiumType from invalid Int value 3", underlyingError: nil)) [DiscordKitCore] Error decoding message
```

**Comment by cryptoAlgorithm** [comment]
Oh, this is a different issue from the other hang on login problem. Looks like this is due to Discord adding a new PremiumType, by any chance do your account(s) have Discord Nitro Basic?

**Comment by AstralNexus25** [comment]
> Oh, this is a different issue from the other hang on login problem. Looks like this is due to Discord adding a new PremiumType, by any chance do your account(s) have Discord Nitro Basic?

Nope, neither of my accounts have nitro.

**Comment by crystall1nedev** [comment]
> Oh, this is a different issue from the other hang on login problem. Looks like this is due to Discord adding a new PremiumType, by any chance do your account(s) have Discord Nitro Basic?

Mine does, at least.

**Comment by cryptoAlgorithm** [comment]
@crystall1nedev Your issue appears to be a separate one from the OPs. Please open a separate issue (as it is due to unrecognised discord premium types).

**Comment by egor-ryashin** [comment]
I have the same issue, but no logs in the directory.

**Comment by therealhubbit** [comment]
same issue as op here

**Comment by egor-ryashin** [comment]
I've got this from debug logging
```
2023-08-06T22:50:00+0300 warning RobustWebSocket : error=keyNotFound(CodingKeys(stringValue: "application", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "d", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"application\", intValue: nil) (\"application\").", underlyingError: nil)) [DiscordKitCore] Error decoding message
```

**Comment by Blind-Joe** [comment]
Same problem here. Infinite loading after login / qr code scan on just bought macbook m1

**Comment by aljustiet** [comment]
Some problem too

**Comment by randompea** [comment]
same.

**Comment by zeronullempty** [comment]
Ditto

**Comment by RWCoding58** [comment]
Same, both phone number and email don't work. Strangely, it knows my account's using two-factor auth, but it doesn't load after entering the code.

**Comment by cryptoAlgorithm** [comment]
@Blind-Joe @aljustiet @randompea @zeronullempty @RWCoding58 could you guys try out [this nightly build](https://cdn.discordapp.com/attachments/973173299037216768/1126515333029707816/swiftcord-canary-rc.zip)? It contains fixes which might resolve your issue. The build is also available through Swiftcord's Discord server, so do join that for the latest updates and faster support.

**Comment by RWCoding58** [comment]
> @Blind-Joe @aljustiet @randompea @zeronullempty @RWCoding58 could you guys try out [this nightly build](https://cdn.discordapp.com/attachments/973173299037216768/1126515333029707816/swiftcord-canary-rc.zip)? It contains fixes which might resolve your issue. The build is also available through Swiftcord's Discord server, so do join that for the latest updates and faster support.

nope, still stuck for me

**Comment by AstralNexus25** [comment]
> @Blind-Joe @aljustiet @randompea @zeronullempty @RWCoding58 could you guys try out [this nightly build](https://cdn.discordapp.com/attachments/973173299037216768/1126515333029707816/swiftcord-canary-rc.zip)? It contains fixes which might resolve your issue. The build is also available through Swiftcord's Discord server, so do join that for the latest updates and faster support.

This does fix some issues, but I still can't log in. If I use CMD+, I can enter settings, and my account name and details show up though!
<img width="828" alt="SCR-20230829-sqee-2" src="https://github.com/SwiftcordApp/Swiftcord/assets/96607325/acf7441f-94da-4c88-89d9-6246b073bc1e">

**Comment by cryptoAlgorithm** [comment]
[Swiftcord.zip](https://github.com/SwiftcordApp/Swiftcord/files/12714089/Swiftcord.zip)

This build seems to fix this issue according to some people, in the Discord server, experiencing the same problem. Give it a shot! (Do note, as always, since this is an unsigned build you'll have to right click > open to get past the macOS warning)

@RWCoding58 @AstralNexus25

**Comment by cryptoAlgorithm** [comment]
> Leaving this here:
> 
> ```
> evaluna@Evas-MacBookPro181 ~ % /Applications/Swiftcord.app/Contents/MacOS/Swiftcord 
> 2023-07-26T03:52:37-0400 info RobustWebSocket : version=9 ws=wss://gateway.discord.gg/?v=9&encoding=json&compress=zlib-stream [DiscordKitCore] [CONNECT]
> 2023-07-26T03:52:37-0400 warning RobustWebSocket : [DiscordKitCore] Reconnection in progress, not reconnecting
> 2023-07-26T03:52:37-0400 info RobustWebSocket : [DiscordKitCore] [CONNECTED]
> 2023-07-26T03:52:37-0400 info RobustWebSocket : heartbeat_interval=41250 [DiscordKitCore] [HELLO]
> 2023-07-26T03:52:37-0400 info RobustWebSocket : intents=nil [DiscordKitCore] [IDENTIFY]
> 2023-07-26T03:52:38-0400 warning RobustWebSocket : error=dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "d", intValue: nil), CodingKeys(stringValue: "user", intValue: nil), CodingKeys(stringValue: "premium_type", intValue: nil)], debugDescription: "Cannot initialize PremiumType from invalid Int value 3", underlyingError: nil)) [DiscordKitCore] Error decoding message
> ```

@crystall1nedev Could you check if the issue #170 is relevant to your issue? The build linked in the previous comment should also help.

**Comment by AstralNexus25** [comment]
> [Swiftcord.zip](https://github.com/SwiftcordApp/Swiftcord/files/12714089/Swiftcord.zip)
> 
> This build seems to fix this issue according to some people, in the Discord server, experiencing the same problem. Give it a shot! (Do note, as always, since this is an unsigned build you'll have to right click > open to get past the macOS warning)
> 
> @RWCoding58 @AstralNexus25

Yess! This build fixes all the issues mentioned in this post. Thanks for your help!

**Comment by cryptoAlgorithm** [comment]
Alright, thats great, hope this also resolves #170!

**Comment by RWCoding58** [comment]
yep, login works now

**Comment by khurshid-alam** [comment]
It is not resolved for me. Tried latest release version from releases and attached zip from here on Air M1 Ventura.

I am getting these errors after logging in by scanning qr. I don't have anything premium. All free.

```
2023-10-11T15:00:37+0530 warning RobustWebSocket : [DiscordKitCore] Already reconnecting, not reconnecting
rerender server
rerender server
rerender server
2023-10-11T15:00:43+0530 info RobustWebSocket : version=9 ws=wss://gateway.discord.gg/?v=9&encoding=json&compress=zlib-stream [DiscordKitCore] [CONNECT]
2023-10-11T15:00:44+0530 info RobustWebSocket : [DiscordKitCore] [CONNECTED]
2023-10-11T15:00:44+0530 warning RobustWebSocket : error=The data couldn’t be read because it isn’t in the correct format. [DiscordKitCore] Error decoding message
```

It keeps repeating. 

What could be the issue ?

@cryptoAlgorithm
