### ISSUE TITLE
[Enhancement]: missing shift+enter functionality

### ISSUE THREAD

**Issue by Duskiee** [SwiftcordApp/Swiftcord#169]
### Describe Your Request

in the original discord client, using shift+enter would create a new line rather than sending the message.

### Category

Sending messages

**Comment by cryptoAlgorithm** [comment]
Hi, it appears that this has already been implemented, but as ⌥ + Enter instead. I believe this was done as that was the default keybind provided by SwiftUI, so we decided to follow along. Thanks for using Swiftcord!
