### ISSUE TITLE
[Bug]: Stuck after login - Nitro Basic

### ISSUE THREAD

**Issue by tails618** [SwiftcordApp/Swiftcord#170]
### Describe the Bug

**Bug Description**
When I login, it spins endlessly.

**Actual Behaviour**
Scan QR code, click sign in, loads forever

**Expected Behavior**
It logs me in and loads Discord

### Reproducing the Bug

1. Enter username/password or scan QR code
2. Sign in
3. Watch it not load

### Version

0.6.1

### Category

Login

### Additional Info

This is similar to issue #167 but I have Nitro Basic, which as mentioned in that PR may be the issue.

**Comment by cryptoAlgorithm** [comment]
Hi, https://github.com/SwiftcordApp/Swiftcord/issues/167#issuecomment-1733401849 could you please test the build linked in this comment? It updates the capabilities set sent when identifying, which changes the ready object's schema and should fix this issue.

**Comment by bitfl0wer** [comment]
That build fixed it for me at least ^^

**Comment by cryptoAlgorithm** [comment]
Cool, I will be closing this issue then :)
