### ISSUE TITLE
[Bug]: Having UI layout overlaps

### ISSUE THREAD

**Issue by egor-ryashin** [SwiftcordApp/Swiftcord#175]
### Describe the Bug

**Bug Description**
![image](https://github.com/SwiftcordApp/Swiftcord/assets/14215045/9e80b470-7db1-4196-b2a1-9ca7dbddc5c6)

**Actual Behaviour**

**Expected Behavior**

### Reproducing the Bug

1...
2...
3...
...

### Version

0.7.0 

### Category

Other

**Comment by cryptoAlgorithm** [comment]
Hi @egor-ryashin, thanks for reporting this. This appears to be a known issue due to SwiftUI incompatibilities present in macOS Monterey. I am very sorry but I am unable to work on a fix as I no longer have a machine on Monterey.
