### ISSUE TITLE
[Bug]: Window caption bar layout broken

### ISSUE THREAD

**Issue by boozook** [SwiftcordApp/Swiftcord#181]
### Describe the Bug

**Bug Description**

Strange behaviour of window caption bar, sidebar part. "Direct messages" presenting twice and covers list items.

**Actual Behaviour**

1. "Direct messages" shows twice: seems to one for caption bar, another one for list/table's title
2. "Direct messages" __covers list items__ of the sidebar

**Expected Behavior**

- One "Direct messages" - window caption only,
- "Direct messages" doesn't covers list items

### Reproducing the Bug

1. Install 0.7.1(8)
2. Login
3. Look at sidebar

### Version

App: 0.7.1

OS: 13.6.1

### Category

Layout

### Screenshots

<img width="440" alt="Screenshot 2023-11-10 at 14 59 54" src="https://github.com/SwiftcordApp/Swiftcord/assets/888526/9cff591e-13e9-4a23-9675-d614aae8ffdf">

**Comment by boozook** [comment]
So workaround is to update macOS?)) Okay.

**Comment by boozook** [comment]
Really, OS update fixes this 🤦🏻‍♂️

**Comment by cryptoAlgorithm** [comment]
> Really, OS update fixes this 🤦🏻‍♂️

Glad to hear this issue is resolved. For documentation purposes, what macOS version is the issue resolved on? (i.e. the one that you're currently running)

**Comment by boozook** [comment]
Was: Ventura 13.6.0 and 13.6.1
Now and issue fixed on: Sonoma 14.any
