### ISSUE TITLE
Can't compile from source

### ISSUE THREAD

**Issue by zohaad** [SwiftcordApp/Swiftcord#42]
**Describe the bug**
Can't compile from source:

`Dependencies could not be resolved because no versions of 'lottie-ios' match the requirement 3.3.0..<4.0.0 and root depends on 'lottie-ios' 3.3.0..<4.0.0.`

**To Reproduce**
Xcode -> Source Control -> Clone...

**Comment by Candygoblen123** [comment]
yeah, there seems to be some issue with Xcode's package cashing, and you have to reset them whenever you do a fresh clone of the repo.

**Comment by cryptoAlgorithm** [comment]
Hi, I have encountered this issue quite a few times, and the only solution is to clear the package cache right after cloning. Also, using the built in Xcode git integration usually leads to trouble, I recommend you use git on the command line and close Xcode when doing major operations like checking out branches (if not your `xcodeproj` might get corrupted.

**Comment by cryptoAlgorithm** [comment]
@zohaad please follow up if clearing the package cache fixes the issue. I'll close this issue if its fixed.

**Comment by zohaad** [comment]
I can get it compiling now, thank you @selimgr.
