### ISSUE TITLE
Message field does not wrap

### ISSUE THREAD

**Issue by cryptoAlgorithm** [SwiftcordApp/Swiftcord#45]
**Describe the bug**
When typing a long message into the message field, the text does not wrap once it hits the end of the field.
Although newlines work (opt + return), the text does not wrap anymore like it did before with `TextEditor`

**To Reproduce**

1. Type very long text in the message field
2. Notice how the text does not scroll, but you can still input text into the field
3. Send the message and note that the text that was entered beyond the width of the field is present

**Expected behavior**
The text wraps to the next line

**Screenshots**
#### Note the cut-off 't' that appears after the cursor
<img width="728" alt="Screenshot 2022-05-26 at 11 46 25 AM" src="https://user-images.githubusercontent.com/64193267/170411931-299e9c17-3c67-4525-b357-4e0d7c52d2db.png">

**Additional context**
Text wrapping used to work while a `TextEditor` was used, but newlines didn't. Now, its the opposite xD

**Comment by charxene** [comment]
Was alt-enter handling the reason for switching from Text to TextField? I think we should explore other options for handling enter as a commit action and alt enter as an edit action.

**Comment by cryptoAlgorithm** [comment]
Yeah, among other issues that TextEditor brought, like a hardcoded background (someone figured how to override it with a transparent color), and no option for a placeholder hint. Also, there were other issues using it with a ScrollView. The other option is to use AppKit, which allows handling of the raw keydown events, but was very tough.

**Comment by cryptoAlgorithm** [comment]
I might use [swiftui-introspect](https://github.com/siteline/SwiftUI-Introspect) to access the low level NSTextView of the TextEditor to handle keyDown events 🤔

**Comment by cryptoAlgorithm** [comment]
This appears to be fixed in macOS 13, irregardless of whether Xcode 13 or 14 is used to build Swiftcord. So, it appears to be some SwiftUI 'bug' (or maybe its a bug in macOS 13 that fixes this as a side effect?) that was fixed in macOS 13. Either ways, the 'fixed' behaviour in macOS 13 is not what I want (it scrolls horizontally when the field overflows instead of wrapping vertically), so I'll still have to figure out some other solution for this.

**Comment by cryptoAlgorithm** [comment]
Moved to #75
