### ISSUE TITLE
Send attachments from clipboard

### ISSUE THREAD

**Issue by jarodise** [SwiftcordApp/Swiftcord#48]
It's not really a bug per se, something I do very often is to paste an image into the input field, I find that it's not supported yet in Swiftcord, would be nice to have it in future iterations. 

Thanks for creating this project!

**Comment by cryptoAlgorithm** [comment]
Thanks for this suggestion. It has been on my mind for a long time, since dragging and dropping into the message field or pasting files is quite important for me too :) I'll add it soon, most likely in the following days :)

**Comment by cryptoAlgorithm** [comment]
This is being worked on at the `drag-n-drop` branch - #52
