### ISSUE TITLE
Weird menu bar item behaviour 

### ISSUE THREAD

**Issue by pozm** [SwiftcordApp/Swiftcord#56]
**Describe the bug**
when clicking any menu items (bar at top of screen) they show up for a split second and then disappear, not to mention getting them to trigger is janky for some reason 
**To Reproduce**
1. click any menu item

**Expected behavior**
for the dropdown to show as intended and stay until unfocused
**Screenshots**
https://user-images.githubusercontent.com/44528100/171665531-b5167f99-097a-479e-b293-9443d1e21a70.mov
**Logs**

**Additional context**

**Comment by cryptoAlgorithm** [comment]
Hi, thanks for creating an issue. I observed this problem earlier, but can't reproduce it anymore on the latest commit. 

https://user-images.githubusercontent.com/64193267/171843192-6d5a2160-79da-49d4-819f-94772bde1ff9.mov

Btw, your screen recording doesn't play

**Comment by pozm** [comment]
Ah sorry i hadn't tried building from latest release (used "nightly" build).

**Comment by cryptoAlgorithm** [comment]
The nightly release should be a build of the latest release, though. Is the issue resolved for you?

**Comment by pozm** [comment]
It is, i must of used an older release

**Comment by cryptoAlgorithm** [comment]
Thanks 😄
