### ISSUE TITLE
Clicking # should open a channel list

### ISSUE THREAD

**Issue by Rex501st** [SwiftcordApp/Swiftcord#74]
When the app is minimized or the sidebar is closed, the # button should open the sidebar or open a popover list of all channels in the server. 

![image](https://user-images.githubusercontent.com/25782090/178028177-ba9f30d3-43ad-4f96-94fb-e491fe2c259c.png)

This would improve the UX and would be logical for when the app is docked to a side of the screen.

Keep up the great work!

**Comment by cryptoAlgorithm** [comment]
I will consider this. Initially, I was trying to prevent the sidebar from collapsing in the first place, but it turned out to be basically impossible.

**Comment by cryptoAlgorithm** [comment]
@Rex501st Here's how the fix looks like
<video src="https://user-images.githubusercontent.com/64193267/178092474-baa116e0-a3fe-4d2f-a1be-a19586568871.mov" />

**Comment by Rex501st** [comment]
> @Rex501st Here's how the fix looks like
> 
>  Screen.Recording.2022-07-09.at.1.06.28.PM.mov

Looks fantastic!
