### ISSUE TITLE
macOS 13 "Megathread"

### ISSUE THREAD

**Issue by cryptoAlgorithm** [SwiftcordApp/Swiftcord#75]
A megathread for penning down everything macOS 13 breaks/fixes

macOS 13 is still in beta 1, so hopefully these bugs get ironed out soon.

**Comment by cryptoAlgorithm** [comment]
**Fixes**
* Text selection doesn't break text wrapping - previously the text would be forced into one line when selected, no matter how long it was
* TextField now scrolls horizontally, so long messages on a single line will not be simply clipped off once they're longer than the field

**Comment by cryptoAlgorithm** [comment]
**Breaks**
* Horrible performance drops after scrolling anything scrollable, most noticeable after scrolling for 2 or more pages
* Toolbar above server and channel list is ruined, with dividers in the wrong place and broken paddings (see below)
* Using `NSApp.sendAction(Selector(("showPreferencesWindow:")), to: nil, from: nil)` to open the preferences window no longer works - workaround: removed settings button in user footer
* Channel list sidebar randomly starts collapsed, regardless if it was previously collapsed

<img width="383" alt="Screenshot 2022-07-09 at 1 47 27 PM" src="https://user-images.githubusercontent.com/64193267/178093430-00495edf-fe35-4452-b029-b99a535c4474.png">

**Comment by BomberFish** [comment]
Sidebar extends into the titlebar?
<img width="147" alt="  2022-07-09 at 16 16 16" src="https://user-images.githubusercontent.com/87151697/178121341-e614ba74-7e8d-4f35-95cb-4dfc1a0aa52b.png">

**Comment by cryptoAlgorithm** [comment]
> Toolbar above server and channel list is ruined, with dividers in the wrong place and broken paddings (see below)

@BomberFish yeah, it's a known issue, I think it's caused by the offsets and paddings being broken

**Comment by OpenSource03** [comment]
> A megathread for penning down everything macOS 13 breaks/fixes
> 
> macOS 13 is still in beta 1, so hopefully these bugs get ironed out soon.

Slight correction, it's already in beta 3, pending public beta soon :)

**Comment by cryptoAlgorithm** [comment]
@OpenSource03 right, that means there's something up with my macOS install. It isn't finding those new updates...

**Comment by cryptoAlgorithm** [comment]
@OpenSource03 After updating to macOS 13 beta 3 and testing, the behaviour is largely the same except that the sluggish scrolling performance is greatly improved, but not as smooth as it was in macOS 12.

**Comment by cryptoAlgorithm** [comment]
macOS 13 beta 4 still hasn't resolved the performance issues while scrolling fast. I verified that the performance on macOS 12.4 (on the same Mac) hasn't dropped on the latest commit, so its solely a macOS 13 issue

**Comment by cryptoAlgorithm** [comment]
With macOS 13 soon to be released, I believe I can safely conclude that any bug present in beta 10/11 will not be fixed before the stable release, which is quite unfortunate. The aforementioned scrolling regression has been slightly improved, but not back to the performance it once had on macOS 12.

**Comment by cryptoAlgorithm** [comment]
I will be closing this as any "bugs" present at this stage aren't going away anytime soon. Remediations for certain issues such as that scrolling performance bug, issues with a scrollbar being present in the toolbar and erroneous lines in the channel list area are being worked on at the `i-am-speed` branch
