### ISSUE TITLE
When docked to a side of the screen, the channel list should collapse and the message pane should stay the same and instead of expanding. 

### ISSUE THREAD

**Issue by Rex501st** [SwiftcordApp/Swiftcord#84]
**Describe the bug**
When collapsing the channel list again via the “#” button, the window should resize to what the state was prior to being expanded

**To Reproduce**

1. Dock the app to the side of the screen and reduce the size
2. Press #
3. Find your channel, and press #
4. When hiding the channel list, the window size doesn't go back to the minimized state.

**Expected behavior**
When pressing the # button to collapse the channel list, the channel list should get smaller, and the chat display should stay the same size. At the current moment, the chat gets bigger while the channel lists collapses.

**Comment by cryptoAlgorithm** [comment]
Hmm, I cant seem to reproduce this. When I resize the window to as small as it would go, press # and select another channel, then drag the channel list to close it, the window size never changes. When I open the channel list again, it doesn't affect the size of the window. 

I assume by docking the window to the size of the screen you mean just resizing the window to take up a small width at the right of the screen?

**Comment by Rex501st** [comment]
> Hmm, I cant seem to reproduce this. When I resize the window to as small as it would go, press # and select another channel, then drag the channel list to close it, the window size never changes. When I open the channel list again, it doesn't affect the size of the window.
> 
> I assume by docking the window to the size of the screen you mean just resizing the window to take up a small width at the right of the screen?

Correct, apologies for the miscommunication
