### ISSUE TITLE
[Bug]: Badge duplication & overlap

### ISSUE THREAD

**Issue by pozm** [SwiftcordApp/Swiftcord#86]
**Describe the bug**

For some reason my nitro badge is being duplicated and overlapped ontop of my hypesquad badge. idk if this will occur with other badges or if it happens with a set amount etc. 
**To Reproduce**

Open a users profile who has HS balance & nitro badges

**Expected behavior**
No duplication and or overlap
**Screenshots**
Swiftcord:
<img width="244" alt="image" src="https://user-images.githubusercontent.com/44528100/179367930-b1a2b538-79c8-41b6-956b-68fbc7b75c0c.png">

standard client:
<img width="310" alt="image" src="https://user-images.githubusercontent.com/44528100/179367956-b2338a60-8277-4139-a862-ed94479c4596.png">

**Logs**

**Additional context**

**Comment by cryptoAlgorithm** [comment]
@pozm Really sorry for not reading this issue earlier! Does this issue happen with al users with nitro and a hype squad badge, or only this particular user/combination of badges?

PS: I usually respond way faster if you ping me in the Swiftcord discord server :)

**Comment by pozm** [comment]
No problems, everyone is busy.

I've looked into it afterwards and it seems like nitro (and booster) badges only show up for the account currently logged in. So i can't really nail down which badge is actually causing it cause it shows up for no one else lol. It may be worth opening another issue about the issue i've came across though, as if you want to have 1:1 parity with std client then it will be needed. 

Thank you

**Comment by cryptoAlgorithm** [comment]
Right. The nitro issue is something I was trying to fix, but couldn't figure out the API responsible for returning the nitro status of a user (the `premium_type` for other users is always `nil`). I unfortunately don't have nitro, so I'll most probably work with one of my contributors to squash this bug. (@Candygoblen123) Thanks for this report!

**Comment by cryptoAlgorithm** [comment]
@Candygoblen123 Could you take a look at this when possible? Since you have nitro, you might be able to repro this.

**Comment by cryptoAlgorithm** [comment]
@pozm, I figured out the cause of this. I'll see if I can fix it, but it doesn't seem like an easy fix.

**Comment by cryptoAlgorithm** [comment]
@pozm This is now fixed. You can grab the latest nightly version to test it out, and as always, thanks for using Swiftcord :)
<img width="387" alt="Screenshot 2022-09-03 at 3 04 36 PM" src="https://user-images.githubusercontent.com/64193267/188259981-8af70a78-2d61-47e0-9281-5410533dd448.png">
