### ISSUE TITLE
Compile/Run Swiftcord on older macOS versions

### ISSUE THREAD

**Issue by shijimasoft** [SwiftcordApp/Swiftcord#87]
**It is possible to compile Switftcord on older macOS versions?**

Since **SwitfUI** is a unified GUI framework since macOS 10.15, compiling for older macOS versions should be possible.
I mean, macOS **Catalina and Big Sur** are also capable of running SwiftUI widgets used by Swiftcord.

Is there any problem in compiling on these macOS versions? I can be a tester if necessary.

**Comment by Candygoblen123** [comment]
SwiftUI gets updates with Every OS release, and we use some features that only exist on macOS 11+. While it would be possible to support older OS versions, it would be a huge pain trying to reimplement major SwiftUI features ourselves (Most notably, `AsyncImage` and `Table`, but the ~98 other errors would be a pain to fix as well)

So no unfortunately, it is not as simple as compiling for older versions of macOS.

**Comment by cryptoAlgorithm** [comment]
A few versions back I've tried to compile for macOS 11, and basically most APIs that we relied on (as @Candygoblen123 said) weren't available. iirc, the async `URLSession` APIs also aren't available, which DiscordKit also heavily relies on.

**Comment by shijimasoft** [comment]
That's really sad :_)
Thanks for explaining me the problems
