### ISSUE TITLE
Add Japanese Localisation Support

### ISSUE THREAD

**Issue by sasa8810** [SwiftcordApp/Swiftcord#97]
### Describe Your Request

Please add Japanese as a language!

### Category

Other

### Other Category

Translation

**Comment by cryptoAlgorithm** [comment]
HI there! Thanks for creating this enhancement. Although I do not have the capability to add Japanese translations, you can do so yourself at [Swiftcord's Weblate](https://hosted.weblate.org/projects/swiftcord/swiftcord/#alerts)! No coding knowledge required, just use a simple web UI to enter the translations!
